kind: pipeline
name: deploy

clone:
  depth: 50

steps:

- name: build
  image: anoff/hugo-asciidoctor
  commands:
  - hugo --gc --minify -d _site --baseURL https://anoff.io
  - touch _site/.nojekyll

- name: publish  
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_token
    pages_directory: _site
  when:
    branch:
    - master