# Site settings
title: Andreas Offenhaeuser
description: Andreas' online portfolio and life story. See the pdf download for a classic resume.
# meta tags
meta: IoT internet of things architect developer fullstack javascript automotive
favicon: favicon.ico
url: https://anoff.io
google_analytics: UA-93890295-2

# Build settings
markdown: kramdown

exclude: [vendor]

# legal notice
legal:
  url: https://anoff.io/legal/ # link to a legal page
  text: Legal Notice